## **DataFrame**

### **DataFrames can be created in 3 ways**

#### **1. Using List of Lists** ---> `pd.DataFrame(list)`
#### **2. Using Dictionary** ---> `pd.DataFrame(dictionary)`
#### **3. Using NumPy Array** ---> `pd.DataFrame(array)`

**Note :**
##### **read_csv()** ---> It is used to **read data from a CSV file and create a DataFrame**.

##### **Syntax** ---> `pd.read_csv("file_name.csv")`

### **DataFrame** ---> Combination of **Rows and Columns** ---> **2D Data Structure**

#### Example of Rows ---> `[[1,2,3], [4,5,6], [7,8,9], [10,11,12], [13,14,15]]`

#### Here, **5 Rows** and **3 Columns** are present.

In [114]:
rows=[[1,2,3], [4,5,6], [7,8,9], [10,11,12], [13,14,15]]

In [115]:
import pandas as pd

In [116]:
List_data=pd.DataFrame(rows,columns=['a','b','c'])

In [117]:
print(List_data)

    a   b   c
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12
4  13  14  15

In [118]:
List_data.shape

(5, 3)

### **`Dictionary ---> Dataframe`**
#### Dictionary ---> Dataframe ---> rows & column combination

In [119]:
dict_data={'Name':['Abhi', 'Amit','Vivek'], 'Miney':[1,5,7], 'Financial_Stress':[1,1,0]}

In [120]:
Dict_dataframe=pd.DataFrame(dict_data)

In [121]:
Dict_dataframe

    Name  Miney  Financial_Stress
0   Abhi      1                 1
1   Amit      5                 1
2  Vivek      7                 0

In [122]:
data=pd.read_csv("D:\TuteDude\Machine Learning\PreRequisites\Pandas\student_depression_dataset.csv")

<>:1: SyntaxWarning: invalid escape sequence '\T'
<>:1: SyntaxWarning: invalid escape sequence '\T'
C:\Users\abhis\AppData\Local\Temp\ipykernel_5056\996605313.py:1: SyntaxWarning: invalid escape sequence '\T'
  data=pd.read_csv("D:\TuteDude\Machine Learning\PreRequisites\Pandas\student_depression_dataset.csv")

In [123]:
data

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,5-6 hours,Unhealthy,Class 12,Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,Less than 5 hours,Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,5-6 hours,Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

In [124]:
type(data)

pandas.DataFrame

In [125]:
df=pd.read_csv("student_depression_dataset.csv")

In [126]:
df

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,5-6 hours,Unhealthy,Class 12,Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,Less than 5 hours,Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,5-6 hours,Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

## Data Exploration ---> Attributes & Functions for Dataframe

### **`Attributes`**

#### **1. shape** ---> It provides information about the **number of rows and columns** present in the DataFrame.
#### **Syntax** ---> `df.shape`

#### **2. dtypes** ---> It provides the **data type of each column** in the DataFrame.
#### **Syntax** ---> `df.dtypes`

#### **3. index** ---> It provides the **index labels** of the DataFrame.
#### **Syntax** ---> `df.index`

#### **4. columns** ---> It provides the **names of all the columns** present in the DataFrame.
#### **Syntax** ---> `df.columns`

#### **5. values** ---> It provides the **values stored inside the DataFrame** as an array. (it always returns a 2D numpy array representing the value of column row by row)
#### **Syntax** ---> `df.values`

#### **6. ndim** ---> It provides the **number of dimensions** of the DataFrame.
#### **Syntax** ---> `df.ndim`

#### **7. size** ---> It provides the **total number of elements** present in the DataFrame.
#### **Syntax** ---> `df.size`

#### **8. T** ---> It provides the **transpose** of the DataFrame, where rows become columns and columns become rows.
#### **Syntax** ---> `df.T`

In [127]:
df.shape

(27901, 18)

In [128]:
df.dtypes

id                                         int64
Gender                                       str
Age                                      float64
City                                         str
Profession                                   str
Academic Pressure                        float64
Work Pressure                            float64
CGPA                                     float64
Study Satisfaction                       float64
Job Satisfaction                         float64
Sleep Duration                               str
Dietary Habits                               str
Degree                                       str
Have you ever had suicidal thoughts ?        str
Work/Study Hours                         float64
Financial Stress                         float64
Family History of Mental Illness             str
Depression                                 int64
dtype: object

In [129]:
df.index

RangeIndex(start=0, stop=27901, step=1)

In [130]:
df.columns

Index(['id', 'Gender', 'Age', 'City', 'Profession', 'Academic Pressure',
       'Work Pressure', 'CGPA', 'Study Satisfaction', 'Job Satisfaction',
       'Sleep Duration', 'Dietary Habits', 'Degree',
       'Have you ever had suicidal thoughts ?', 'Work/Study Hours',
       'Financial Stress', 'Family History of Mental Illness', 'Depression'],
      dtype='str')

In [131]:
df.values

array([[2, 'Male', 33.0, ..., 1.0, 'No', 1],
       [8, 'Female', 24.0, ..., 2.0, 'Yes', 0],
       [26, 'Male', 31.0, ..., 1.0, 'Yes', 0],
       ...,
       [140689, 'Male', 31.0, ..., 2.0, 'No', 0],
       [140690, 'Female', 18.0, ..., 5.0, 'No', 1],
       [140699, 'Male', 27.0, ..., 3.0, 'Yes', 1]],
      shape=(27901, 18), dtype=object)

In [132]:
df.values[0]

array([2, 'Male', 33.0, 'Visakhapatnam', 'Student', 5.0, 0.0, 8.97, 2.0,
       0.0, '5-6 hours', 'Healthy', 'B.Pharm', 'Yes', 3.0, 1.0, 'No', 1],
      dtype=object)

In [133]:
df.ndim

2

In [134]:
df.size

502218

In [135]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,27891,27892,27893,27894,27895,27896,27897,27898,27899,27900
id,2,8,26,30,32,33,52,56,59,62,...,140645,140669,140672,140681,140684,140685,140686,140689,140690,140699
Gender,Male,Female,Male,Female,Female,Male,Male,Female,Male,Male,...,Female,Female,Female,Male,Male,Female,Male,Male,Female,Male
Age,33.0,24.0,31.0,28.0,25.0,29.0,30.0,30.0,28.0,31.0,...,28.0,20.0,24.0,23.0,31.0,27.0,27.0,31.0,18.0,27.0
City,Visakhapatnam,Bangalore,Srinagar,Varanasi,Jaipur,Pune,Thane,Chennai,Nagpur,Nashik,...,Thane,Indore,Hyderabad,Srinagar,Lucknow,Surat,Ludhiana,Faridabad,Ludhiana,Patna
Profession,Student,Student,Student,Student,Student,Student,Student,Student,Student,Student,...,Student,Student,Student,Student,Student,Student,Student,Student,Student,Student
Academic Pressure,5.0,2.0,3.0,3.0,4.0,2.0,3.0,2.0,3.0,2.0,...,4.0,3.0,3.0,3.0,2.0,5.0,2.0,3.0,5.0,4.0
Work Pressure,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
CGPA,8.97,5.9,7.03,5.59,8.13,5.7,9.54,8.04,9.79,8.38,...,7.77,7.72,6.02,6.0,7.27,5.75,9.4,6.61,6.88,9.24
Study Satisfaction,2.0,5.0,5.0,2.0,3.0,3.0,4.0,4.0,1.0,3.0,...,3.0,5.0,2.0,2.0,5.0,5.0,3.0,4.0,2.0,1.0
Job Satisfaction,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Sleep Duration,5-6 hours,5-6 hours,Less than 5 hours,7-8 hours,5-6 hours,Less than 5 hours,7-8 hours,Less than 5 hours,7-8 hours,Less than 5 hours,...,Less than 5 hours,Less than 5 hours,7-8 hours,More than 8 hours,7-8 hours,5-6 hours,Less than 5 hours,5-6 hours,Less than 5 hours,Less than 5 hours
Dietary Habits,Healthy,Moderate,Healthy,Moderate,Moderate,Healthy,Healthy,Unhealthy,Moderate,Moderate,...,Unhealthy,Moderate,Moderate,Healthy,Moderate,Unhealthy,Healthy,Unhealthy,Healthy,Healthy
Degree,B.Pharm,BSc,BA,BCA,M.Tech,PhD,BSc,Class 12,B.Ed,LLB,...,MSc,Class 12,B.Arch,MBBS,B.Com,Class 12,MSc,MD,Class 12,BCA
Have you ever had suicidal thoughts ?,Yes,No,No,Yes,Yes,No,No,No,Yes,Yes,...,No,Yes,No,Yes,Yes,Yes,No,No,Yes,Yes
Work/Study Hours,3.0,3.0,9.0,4.0,1.0,4.0,1.0,0.0,12.0,2.0,...,2.0,8.0,8.0,12.0,6.0,7.0,0.0,12.0,10.0,2.0
Financial Stress,1.0,2.0,1.0,5.0,1.0,1.0,2.0,1.0,3.0,5.0,...,5.0,1.0,2.0,4.0,1.0,1.0,3.0,2.0,5.0,3.0
Family History of Mental Illness,No,Yes,Yes,Yes,No,No,No,Yes,No,No,...,No,No,No,No,Yes,Yes,Yes,No,No,Yes
Depression,1,0,0,1,0,0,0,0,1,1,...,1,0,0,0,0,0,0,0,1,1

### **Functions**

#### **1. head()** ---> It provides the **first 5 rows** of the DataFrame by default. (if i want that instead of top 5 rows i want to see fixed number of rowws from the rows, that number i can pass inside the head function parameter)
#### **Syntax** ---> `df.head()` and `df.nead(Number)`

#### **2. tail()** ---> It provides the **last 5 rows** of the DataFrame by default.
#### **Syntax** ---> `df.tail()` and `df.tail(Number)`

#### **3. sample()** ---> It is used to **randomly select rows** from the DataFrame.
#### **Syntax** ---> `df.sample()` and `df.tail(sample)`

#### **4. info()** ---> It provides information about the **DataFrame, columns, data types, and memory usage**.
#### **Syntax** ---> `df.info()`

#### **5. describe()** ---> It provides a **statistical summary** of the numerical columns.
#### **Syntax** ---> `df.describe()`

#### **6. sum()** ---> It calculates the **sum of values** in the DataFrame.
#### **Syntax** ---> `df.sum()`

#### **7. mean()** ---> It calculates the **mean (average)** of the values.
#### **Syntax** ---> `df.mean()`

#### **8. max()** ---> It provides the **maximum value** from the DataFrame.
#### **Syntax** ---> `df.max()`

#### **9. min()** ---> It provides the **minimum value** from the DataFrame.
#### **Syntax** ---> `df.min()`

#### **10. count()** ---> It counts the **non-empty values** in each column.
#### **Syntax** ---> `df.count()`

#### **11. sort_values()** ---> It is used to **sort the DataFrame based on a particular column**.
#### **Syntax** ---> `df.sort_values("column_name")`

#### **12. drop()** ---> It is used to **remove rows or columns** from the DataFrame.
#### **Syntax** ---> `df.drop("column_name", axis=1)`

#### **13. value_counts()** ---> It counts the **number of occurrences of each unique value** in a column.
#### **Syntax** ---> `df["column_name"].value_counts()`

#### **14. isnull()** ---> It checks for **missing values** and returns `True` or `False`.
#### **Syntax** ---> `df.isnull()`

#### **15. dropna()** ---> It is used to **remove rows or columns containing missing values**.
#### **Syntax** ---> `df.dropna()`

#### **16. fillna()** ---> It is used to **fill missing values** with a specified value.
#### **Syntax** ---> `df.fillna(value)`

In [136]:
df.head()

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0

In [137]:
df.head(3)

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0

In [138]:
df.tail()

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,5-6 hours,Unhealthy,Class 12,Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,Less than 5 hours,Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,5-6 hours,Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

In [139]:
df.tail(3)

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,5-6 hours,Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

In [140]:
df.sample()

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
5185,26175,Male,33.0,Varanasi,Student,1.0,0.0,9.6,4.0,0.0,More than 8 hours,Unhealthy,B.Ed,No,7.0,1.0,Yes,0

In [141]:
df.sample(5)

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
20736,104914,Female,28.0,Delhi,Student,5.0,0.0,9.39,5.0,0.0,Less than 5 hours,Moderate,B.Com,No,5.0,5.0,No,1
9976,50448,Male,28.0,Varanasi,Student,1.0,0.0,8.17,1.0,0.0,More than 8 hours,Moderate,BE,No,4.0,3.0,No,0
22081,111532,Male,34.0,Visakhapatnam,Student,1.0,0.0,7.79,3.0,0.0,Less than 5 hours,Healthy,M.Ed,No,6.0,2.0,Yes,0
18740,94834,Female,24.0,Bangalore,Student,4.0,0.0,8.08,3.0,0.0,Less than 5 hours,Unhealthy,B.Arch,Yes,0.0,4.0,Yes,1
23209,117014,Female,29.0,Bangalore,Student,3.0,0.0,7.94,3.0,0.0,More than 8 hours,Moderate,B.Ed,Yes,10.0,5.0,Yes,1

In [142]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 27901 entries, 0 to 27900
Data columns (total 18 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   id                                     27901 non-null  int64
 1   Gender                                 27901 non-null  str
 2   Age                                    27901 non-null  float64
 3   City                                   27901 non-null  str
 4   Profession                             27901 non-null  str
 5   Academic Pressure                      27901 non-null  float64
 6   Work Pressure                          27901 non-null  float64
 7   CGPA                                   27901 non-null  float64
 8   Study Satisfaction                     27901 non-null  float64
 9   Job Satisfaction                       27901 non-null  float64
 10  Sleep Duration                         27901 non-null  str
 11  Dietary Habits                         27901 non-null  str
 12  Degree                                 27901 non-null  str
 13  Have you ever had suicidal thoughts ?  27901 non-null  str
 14  Work/Study Hours                       27901 non-null  float64
 15  Financial Stress                       27898 non-null  float64
 16  Family History of Mental Illness       27901 non-null  str
 17  Depression                             27901 non-null  int64
dtypes: float64(8), int64(2), str(8)
memory usage: 3.8 MB

In [143]:
df.describe()

,id,Age,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Work/Study Hours,Financial Stress,Depression
count,27901.000000,27901.000000,27901.000000,27901.000000,27901.000000,27901.000000,27901.000000,27901.000000,27898.000000,27901.000000
mean,70442.149421,25.822300,3.141214,0.000430,7.656104,2.943837,0.000681,7.156984,3.139867,0.585499
std,40641.175216,4.905687,1.381465,0.043992,1.470707,1.361148,0.044394,3.707642,1.437347,0.492645
min,2.000000,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
25%,35039.000000,21.000000,2.000000,0.000000,6.290000,2.000000,0.000000,4.000000,2.000000,0.000000
50%,70684.000000,25.000000,3.000000,0.000000,7.770000,3.000000,0.000000,8.000000,3.000000,1.000000
75%,105818.000000,30.000000,4.000000,0.000000,8.920000,4.000000,0.000000,10.000000,4.000000,1.000000
max,140699.000000,59.000000,5.000000,5.000000,10.000000,5.000000,4.000000,12.000000,5.000000,1.000000

### **Before Data Cleaning**

#### Before starting data cleaning, we first need to check whether the data contains any **missing values** or **duplicate values**.

#### Missing value or not ---> **isnull()** ---> It is used to **check whether the data contains any missing values**. It returns `True` if the value is missing, otherwise it returns `False`.

#### **Syntax** ---> `df.isnull()`

In [144]:
df.isnull()

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
27897,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
27898,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
27899,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
27900,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [145]:
df.isnull().sum

<bound method DataFrame.sum of           id  Gender    Age   City  Profession  Academic Pressure  \
0      False   False  False  False       False              False
1      False   False  False  False       False              False
2      False   False  False  False       False              False
3      False   False  False  False       False              False
4      False   False  False  False       False              False
...      ...     ...    ...    ...         ...                ...
27896  False   False  False  False       False              False
27897  False   False  False  False       False              False
27898  False   False  False  False       False              False
27899  False   False  False  False       False              False
27900  False   False  False  False       False              False

       Work Pressure   CGPA  Study Satisfaction  Job Satisfaction  \
0              False  False               False             False
1              False  False               False             False
2              False  False               False             False
3              False  False               False             False
4              False  False               False             False
...              ...    ...                 ...               ...
27896          False  False               False             False
27897          False  False               False             False
27898          False  False               False             False
27899          False  False               False             False
27900          False  False               False             False

       Sleep Duration  Dietary Habits  Degree  \
0               False           False   False
1               False           False   False
2               False           False   False
3               False           False   False
4               False           False   False
...               ...             ...     ...
27896           False           False   False
27897           False           False   False
27898           False           False   False
27899           False           False   False
27900           False           False   False

       Have you ever had suicidal thoughts ?  Work/Study Hours  \
0                                      False             False
1                                      False             False
2                                      False             False
3                                      False             False
4                                      False             False
...                                      ...               ...
27896                                  False             False
27897                                  False             False
27898                                  False             False
27899                                  False             False
27900                                  False             False

       Financial Stress  Family History of Mental Illness  Depression
0                 False                             False       False
1                 False                             False       False
2                 False                             False       False
3                 False                             False       False
4                 False                             False       False
...                 ...                               ...         ...
27896             False                             False       False
27897             False                             False       False
27898             False                             False       False
27899             False                             False       False
27900             False                             False       False

[27901 rows x 18 columns]>

In [146]:
import numpy as np
data={'name':['Abhi','Amit','Prabhat','Shivy'],'Package':[8,9,5,17],'Degree':['BTech','MBA','MBBS',np.nan]}

In [147]:
pd.DataFrame(data)

      name  Package Degree
0     Abhi        8  BTech
1     Amit        9    MBA
2  Prabhat        5   MBBS
3    Shivy       17    NaN

In [148]:
pd.DataFrame(data).isnull().sum

<bound method DataFrame.sum of     name  Package  Degree
0  False    False   False
1  False    False   False
2  False    False   False
3  False    False    True>

In [149]:
## missing values ---> nan values in the dataset

#### **duplicated()** ---> It is used to **check whether duplicate values are present in the DataFrame or Series**. It returns `True` for duplicate values and `False` for unique values.

#### **Syntax** ---> `df.duplicated()`

In [150]:
df.duplicated().sum()

np.int64(0)

### Data cleaning
### 1. Missing Values
### 2. Duplicate
### 3. Renaming the column as well

In [151]:
df

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,5-6 hours,Unhealthy,Class 12,Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,Less than 5 hours,Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,5-6 hours,Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

In [152]:
df.rename(columns={'CGPA':'Cgpa', 'Age':'Student_Age'})

,id,Gender,Student_Age,City,Profession,Academic Pressure,Work Pressure,Cgpa,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,5-6 hours,Unhealthy,Class 12,Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,Less than 5 hours,Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,5-6 hours,Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

In [153]:
df

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,5-6 hours,Unhealthy,Class 12,Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,Less than 5 hours,Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,5-6 hours,Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

In [154]:
## In order to make sure that the changes are going to be permanent we can go with inplace parameter

In [155]:
df.rename(columns={'Age':'AGE'},inplace=True)

In [156]:
df

,id,Gender,AGE,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,5-6 hours,Unhealthy,Class 12,Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,Less than 5 hours,Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,5-6 hours,Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

### **Mathematical Functions in DataFrame**

#### **1. `sum()`** ---> It calculates the **sum of all values** present in a column or in multiple columns.
#### **Syntax** ---> `df.sum()`

#### **2. `mean()`** ---> It calculates the **average (mean)** of the values present in a column or multiple columns.
#### **Syntax** ---> `df.mean()`

#### **3. `min()`** ---> It provides the **minimum value** present in a column or multiple columns.
#### **Syntax** ---> `df.min()`

#### **4. `max()`** ---> It provides the **maximum value** present in a column or multiple columns.
#### **Syntax** ---> `df.max()`

#### **5. `median()`** ---> It calculates the **middle value (median)** of the values present in a column or multiple columns.
#### **Syntax** ---> `df.median()`

#### **6. `std()`** ---> It calculates the **standard deviation** of the values.
#### **Syntax** ---> `df.std()`

#### **7. `var()`** ---> It calculates the **variance** of the values (of the columns).
#### **Syntax** ---> `df.var()`

#### **8. `count()`** ---> It counts the **number of non-missing values** present in a column or multiple columns.
#### **Syntax** ---> `df.count()`

#### **9. `prod()`** ---> It calculates the **product of all values** present in a column or multiple columns.
#### **Syntax** ---> `df.prod()`

### **axis Parameter**

#### **axis** ---> It tells us **in which direction we want to perform an operation(Mathematical)** on the DataFrame row wise or column wise.

#### **axis=0** ---> Operation is performed **column-wise**.
#### **axis=1** ---> Operation is performed **row-wise**.

In [157]:
df.sum()

id                                                                              1965406411
Gender                                   MaleFemaleMaleFemaleFemaleMaleMaleFemaleMaleMa...
AGE                                                                               720468.0
City                                     VisakhapatnamBangaloreSrinagarVaranasiJaipurPu...
Profession                               StudentStudentStudentStudentStudentStudentStud...
Academic Pressure                                                                  87643.0
Work Pressure                                                                         12.0
CGPA                                                                           213612.9625
Study Satisfaction                                                                 82136.0
Job Satisfaction                                                                      19.0
Sleep Duration                           5-6 hours5-6 hoursLess than 5 hours7-8 hours5-...
Dietary Habits                           HealthyModerateHealthyModerateModerateHealthyH...
Degree                                   B.PharmBScBABCAM.TechPhDBScClass 12B.EdLLBClas...
Have you ever had suicidal thoughts ?    YesNoNoYesYesNoNoNoYesYesYesYesNoNoYesYesYesYe...
Work/Study Hours                                                                  199687.0
Financial Stress                                                                   87596.0
Family History of Mental Illness         NoYesYesYesNoNoNoYesNoNoYesYesYesYesYesYesYesN...
Depression                                                                           16336
dtype: object

In [158]:
df.values[0]

array([2, 'Male', 33.0, 'Visakhapatnam', 'Student', 5.0, 0.0, 8.97, 2.0,
       0.0, '5-6 hours', 'Healthy', 'B.Pharm', 'Yes', 3.0, 1.0, 'No', 1],
      dtype=object)

In [159]:
df.sum(axis=0)

id                                                                              1965406411
Gender                                   MaleFemaleMaleFemaleFemaleMaleMaleFemaleMaleMa...
AGE                                                                               720468.0
City                                     VisakhapatnamBangaloreSrinagarVaranasiJaipurPu...
Profession                               StudentStudentStudentStudentStudentStudentStud...
Academic Pressure                                                                  87643.0
Work Pressure                                                                         12.0
CGPA                                                                           213612.9625
Study Satisfaction                                                                 82136.0
Job Satisfaction                                                                      19.0
Sleep Duration                           5-6 hours5-6 hoursLess than 5 hours7-8 hours5-...
Dietary Habits                           HealthyModerateHealthyModerateModerateHealthyH...
Degree                                   B.PharmBScBABCAM.TechPhDBScClass 12B.EdLLBClas...
Have you ever had suicidal thoughts ?    YesNoNoYesYesNoNoNoYesYesYesYesNoNoYesYesYesYe...
Work/Study Hours                                                                  199687.0
Financial Stress                                                                   87596.0
Family History of Mental Illness         NoYesYesYesNoNoNoYesNoNoYesYesYesYesYesYesYesN...
Depression                                                                           16336
dtype: object

In [161]:
df.sum(axis=1)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [162]:
df.min(axis=0)

id                                               2
Gender                                      Female
AGE                                           18.0
City                                           3.0
Profession                               Architect
Academic Pressure                              0.0
Work Pressure                                  0.0
CGPA                                           0.0
Study Satisfaction                             0.0
Job Satisfaction                               0.0
Sleep Duration                           5-6 hours
Dietary Habits                             Healthy
Degree                                      B.Arch
Have you ever had suicidal thoughts ?           No
Work/Study Hours                               0.0
Financial Stress                               1.0
Family History of Mental Illness                No
Depression                                       0
dtype: object

In [ ]:
## df.mean() ## df.var()

In [163]:
df.sample(5)

,id,Gender,AGE,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
25034,126137,Female,30.0,Vadodara,Student,3.0,0.0,7.80,4.0,0.0,More than 8 hours,Unhealthy,BA,Yes,9.0,5.0,Yes,1
10088,50986,Female,18.0,Kolkata,Student,5.0,0.0,5.42,5.0,0.0,Less than 5 hours,Moderate,Class 12,Yes,11.0,5.0,No,1
10491,53179,Male,26.0,Hyderabad,Student,5.0,0.0,8.91,4.0,0.0,More than 8 hours,Unhealthy,M.Tech,Yes,4.0,5.0,No,1
27055,136361,Male,28.0,Ahmedabad,Student,3.0,0.0,6.78,5.0,0.0,7-8 hours,Unhealthy,PhD,No,3.0,4.0,No,1
1093,5660,Male,19.0,Ghaziabad,Student,2.0,0.0,6.99,3.0,0.0,5-6 hours,Moderate,Class 12,Yes,7.0,3.0,No,1

In [164]:
df.columns

Index(['id', 'Gender', 'AGE', 'City', 'Profession', 'Academic Pressure',
       'Work Pressure', 'CGPA', 'Study Satisfaction', 'Job Satisfaction',
       'Sleep Duration', 'Dietary Habits', 'Degree',
       'Have you ever had suicidal thoughts ?', 'Work/Study Hours',
       'Financial Stress', 'Family History of Mental Illness', 'Depression'],
      dtype='str')

In [165]:
type(df['Academic Pressure'])

pandas.Series

In [ ]:
## For selecting a column from a dataframe ---> df['col_name']
## for selecting Multiple columns from a dataframe ---> df[['col_1', 'col_2', 'col_3', ...]]

In [166]:
data=df[['AGE','Sleep Duration','Dietary Habits','Work/Study Hours',
       'Financial Stress',]]

In [167]:
data

,AGE,Sleep Duration,Dietary Habits,Work/Study Hours,Financial Stress
0,33.0,5-6 hours,Healthy,3.0,1.0
1,24.0,5-6 hours,Moderate,3.0,2.0
2,31.0,Less than 5 hours,Healthy,9.0,1.0
3,28.0,7-8 hours,Moderate,4.0,5.0
4,25.0,5-6 hours,Moderate,1.0,1.0
...,...,...,...,...,...
27896,27.0,5-6 hours,Unhealthy,7.0,1.0
27897,27.0,Less than 5 hours,Healthy,0.0,3.0
27898,31.0,5-6 hours,Unhealthy,12.0,2.0
27899,18.0,Less than 5 hours,Healthy,10.0,5.0
27900,27.0,Less than 5 hours,Healthy,2.0,3.0

### **Selecting Specific Rows from a DataFrame**

#### **`loc[]`** ---> It is used to select rows or columns using their **labels (names)**. (it fetches the record as per the labelled location of the value)

#### **Syntax** ---> `df.loc[row_label]`

#### **`iloc[]`** ---> It is used to select rows or columns using their **integer positions (index numbers)**. (it fetches the record as per the integer index location of the value)

#### **Syntax** ---> `df.iloc[row_index]`

In [168]:
df.head(2)

,id,Gender,AGE,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0

In [169]:
df.iloc[1000]

id                                                5152
Gender                                            Male
AGE                                               29.0
City                                     Visakhapatnam
Profession                                     Student
Academic Pressure                                  3.0
Work Pressure                                      0.0
CGPA                                              7.94
Study Satisfaction                                 3.0
Job Satisfaction                                   0.0
Sleep Duration                               5-6 hours
Dietary Habits                                Moderate
Degree                                             BSc
Have you ever had suicidal thoughts ?               No
Work/Study Hours                                   2.0
Financial Stress                                   1.0
Family History of Mental Illness                   Yes
Depression                                           0
Name: 1000, dtype: object

In [170]:
df.iloc[500]

id                                                    2591
Gender                                                Male
AGE                                                   21.0
City                                                Mumbai
Profession                                         Student
Academic Pressure                                      1.0
Work Pressure                                          0.0
CGPA                                                  7.09
Study Satisfaction                                     5.0
Job Satisfaction                                       0.0
Sleep Duration                           More than 8 hours
Dietary Habits                                     Healthy
Degree                                                 MCA
Have you ever had suicidal thoughts ?                   No
Work/Study Hours                                       4.0
Financial Stress                                       5.0
Family History of Mental Illness                       Yes
Depression                                               0
Name: 500, dtype: object

In [172]:
## Fetch the records by slicing concept

In [173]:
df.iloc[0:11]

,id,Gender,AGE,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
5,33,Male,29.0,Pune,Student,2.0,0.0,5.70,3.0,0.0,Less than 5 hours,Healthy,PhD,No,4.0,1.0,No,0
6,52,Male,30.0,Thane,Student,3.0,0.0,9.54,4.0,0.0,7-8 hours,Healthy,BSc,No,1.0,2.0,No,0
7,56,Female,30.0,Chennai,Student,2.0,0.0,8.04,4.0,0.0,Less than 5 hours,Unhealthy,Class 12,No,0.0,1.0,Yes,0
8,59,Male,28.0,Nagpur,Student,3.0,0.0,9.79,1.0,0.0,7-8 hours,Moderate,B.Ed,Yes,12.0,3.0,No,1
9,62,Male,31.0,Nashik,Student,2.0,0.0,8.38,3.0,0.0,Less than 5 hours,Moderate,LLB,Yes,2.0,5.0,No,1
10,83,Male,24.0,Nagpur,Student,3.0,0.0,6.10,3.0,0.0,5-6 hours,Moderate,Class 12,Yes,11.0,1.0,Yes,1

In [174]:
## fetch the record starting from index 8 to allof the records
df.iloc[8:]

,id,Gender,AGE,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
8,59,Male,28.0,Nagpur,Student,3.0,0.0,9.79,1.0,0.0,7-8 hours,Moderate,B.Ed,Yes,12.0,3.0,No,1
9,62,Male,31.0,Nashik,Student,2.0,0.0,8.38,3.0,0.0,Less than 5 hours,Moderate,LLB,Yes,2.0,5.0,No,1
10,83,Male,24.0,Nagpur,Student,3.0,0.0,6.10,3.0,0.0,5-6 hours,Moderate,Class 12,Yes,11.0,1.0,Yes,1
11,91,Male,33.0,Vadodara,Student,3.0,0.0,7.03,4.0,0.0,Less than 5 hours,Healthy,BE,Yes,10.0,2.0,Yes,0
12,94,Male,27.0,Kalyan,Student,5.0,0.0,7.04,1.0,0.0,Less than 5 hours,Moderate,M.Tech,No,10.0,1.0,Yes,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,5-6 hours,Unhealthy,Class 12,Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,Less than 5 hours,Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,5-6 hours,Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

In [175]:
## slicing with skipping values

df.iloc[1::2]

,id,Gender,AGE,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
5,33,Male,29.0,Pune,Student,2.0,0.0,5.70,3.0,0.0,Less than 5 hours,Healthy,PhD,No,4.0,1.0,No,0
7,56,Female,30.0,Chennai,Student,2.0,0.0,8.04,4.0,0.0,Less than 5 hours,Unhealthy,Class 12,No,0.0,1.0,Yes,0
9,62,Male,31.0,Nashik,Student,2.0,0.0,8.38,3.0,0.0,Less than 5 hours,Moderate,LLB,Yes,2.0,5.0,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27891,140645,Female,28.0,Thane,Student,4.0,0.0,7.77,3.0,0.0,Less than 5 hours,Unhealthy,MSc,No,2.0,5.0,No,1
27893,140672,Female,24.0,Hyderabad,Student,3.0,0.0,6.02,2.0,0.0,7-8 hours,Moderate,B.Arch,No,8.0,2.0,No,0
27895,140684,Male,31.0,Lucknow,Student,2.0,0.0,7.27,5.0,0.0,7-8 hours,Moderate,B.Com,Yes,6.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,Less than 5 hours,Healthy,MSc,No,0.0,3.0,Yes,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1

In [176]:
## loc[] ---> Location of the given index

In [180]:
df_obj={'name':['Abhi','Vivek','Sumit'], 'Age':[23,22,27],'Package':[8,11,27]}

#### **set_index()**

#### **set_index()** ---> It is used to **set a particular column as the index** of the DataFrame.

#### **Syntax** ---> `df.set_index('column_name')`

In [178]:
df.head(5)

,id,Gender,AGE,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0

In [193]:
data=pd.DataFrame(df_obj)

In [194]:
data

    name  Age  Package
0   Abhi   23        8
1  Vivek   22       11
2  Sumit   27       27

In [195]:
data=data.set_index(['name'])

In [196]:
data.loc['Abhi']

Age        23
Package     8
Name: Abhi, dtype: int64

#### **Fancy Indexing**

#### **Fancy Indexing** ---> It is used to **select multiple specific rows or columns at the same time** by providing a list of index labels or positions.

#### **Using `loc[]`** ---> Select multiple rows using their **labels**.

#### **Syntax** ---> `df.loc[[row_1, row_2, row_3]]`

#### **Using `iloc[]`** ---> Select multiple rows using their **integer positions**.

#### **Syntax** ---> `df.iloc[[0, 2, 4]]`

In [197]:
df.loc[[1,4,7,8,13]]

,id,Gender,AGE,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
7,56,Female,30.0,Chennai,Student,2.0,0.0,8.04,4.0,0.0,Less than 5 hours,Unhealthy,Class 12,No,0.0,1.0,Yes,0
8,59,Male,28.0,Nagpur,Student,3.0,0.0,9.79,1.0,0.0,7-8 hours,Moderate,B.Ed,Yes,12.0,3.0,No,1
13,100,Female,19.0,Rajkot,Student,2.0,0.0,8.52,4.0,0.0,Less than 5 hours,Unhealthy,Class 12,No,6.0,2.0,Yes,0

In [200]:
data.loc[['Abhi','Sumit']]

       Age  Package
name
Abhi    23        8
Sumit   27       27

In [198]:
data.loc['Abhi'::2]

       Age  Package
name
Abhi    23        8
Sumit   27       27

In [201]:
## Even if we are having the labelled index, at the back end the labelled index is also going to have integer indexing only by python

In [202]:
data

       Age  Package
name
Abhi    23        8
Vivek   22       11
Sumit   27       27

In [203]:
'''data ---> Abhi ---> 0
     ---> Vivek ---> 1
     ---> Sumit ---> 2'''

'data ---> Abhi ---> 0\n     ---> Vivek ---> 1\n     ---> Sumit ---> 2'

In [204]:
### Fetching Specific Rows and Specific Columns

In [ ]:
## df[row1:row_n,col_1:col_n]

In [206]:
df.columns

Index(['id', 'Gender', 'AGE', 'City', 'Profession', 'Academic Pressure',
       'Work Pressure', 'CGPA', 'Study Satisfaction', 'Job Satisfaction',
       'Sleep Duration', 'Dietary Habits', 'Degree',
       'Have you ever had suicidal thoughts ?', 'Work/Study Hours',
       'Financial Stress', 'Family History of Mental Illness', 'Depression'],
      dtype='str')

In [208]:
df.loc[0:5,['Gender', 'City', 'Sleep Duration', 'Dietary Habits']]

   Gender           City     Sleep Duration Dietary Habits
0    Male  Visakhapatnam          5-6 hours        Healthy
1  Female      Bangalore          5-6 hours       Moderate
2    Male       Srinagar  Less than 5 hours        Healthy
3  Female       Varanasi          7-8 hours       Moderate
4  Female         Jaipur          5-6 hours       Moderate
5    Male           Pune  Less than 5 hours        Healthy

In [209]:
df.iloc[0:9,0:7]

,id,Gender,AGE,City,Profession,Academic Pressure,Work Pressure
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0
1,8,Female,24.0,Bangalore,Student,2.0,0.0
2,26,Male,31.0,Srinagar,Student,3.0,0.0
3,30,Female,28.0,Varanasi,Student,3.0,0.0
4,32,Female,25.0,Jaipur,Student,4.0,0.0
5,33,Male,29.0,Pune,Student,2.0,0.0
6,52,Male,30.0,Thane,Student,3.0,0.0
7,56,Female,30.0,Chennai,Student,2.0,0.0
8,59,Male,28.0,Nagpur,Student,3.0,0.0

In [ ]:
## Dataset ---> row ---> 1000 rows and 5 columns ---> df.iloc[0:1001,0:5]