In [88]:
import numpy as np
import pandas as pd

In [89]:
data = pd.read_csv('D:\TuteDude\Machine Learning\PreRequisites\Pandas\youtube_2025_dataset_202504061614.csv')
data

<>:1: SyntaxWarning: invalid escape sequence '\T'
<>:1: SyntaxWarning: invalid escape sequence '\T'
C:\Users\abhis\AppData\Local\Temp\ipykernel_17868\1153581564.py:1: SyntaxWarning: invalid escape sequence '\T'
  data = pd.read_csv('D:\TuteDude\Machine Learning\PreRequisites\Pandas\youtube_2025_dataset_202504061614.csv')

,Channel Name,Youtuber Name,Total Videos,Best Video,Avg Video Length (min),Total Subscribers,Members Count,AI Generated Content (%),Neural Interface Compatible,Metaverse Integration Level,Quantum Computing Topics,Holographic Content Rating,Engagement Score,Content Value Index
0,Smith-Ross Labs,Eric Patel,68,VR Challenge: Review 2023,24.8,8264152,303319,9,True,Full,5,3D,130655.44,6.2
1,Sandoval PLC Hub,Cynthia Harrington,128,Nanotech Simulation: Analysis 2024,22.9,8768222,384629,62,False,NaN,4,3D,138624.73,21.4
2,"Jones, Moore and Ho Network",Amanda Walker,282,Metaverse Interface: Analysis 2024,24.0,6163386,361743,31,True,Advanced,6,1D,97442.53,13.5
3,Mitchell-Hooper Labs,Jessica Nelson MD,302,VR Protocol: Review 2023,24.6,4712268,58483,5,False,NaN,15,1D,74500.50,12.0
4,Wilson LLC Studios,Matthew Sherman,129,Nanotech Simulation: Review 2024,24.6,9592017,333873,63,True,NaN,12,3D,151648.85,27.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Flores-Daniel Studios,Jasmine Smith,106,AI Challenge: Experience 2023,22.0,2665835,267828,19,True,Full,1,3D,42146.59,6.4
4996,Spencer and Sons Studios,John Rasmussen,130,VR Challenge: Analysis 2023,26.3,136992,20019,67,True,Full,14,4D,2165.83,29.9
4997,Obrien-Roberts Studios,Lisa Burke,179,AI Challenge: Experience 2023,25.2,2314561,407346,99,True,Advanced,5,1D,36592.98,33.2
4998,King Ltd Hub,Steve Diaz,182,VR Synthesis: Showcase 2023,24.5,6954832,308313,1,True,Basic,9,4D,109955.22,6.6
4999,Henry Ltd Studios,Austin Tate,92,AI Simulation: Showcase 2025,25.2,6785166,23263,52,True,Full,8,3D,107272.81,21.2

In [90]:
df = pd.read_csv('youtube_2025_dataset_202504061614.csv')

In [91]:
df

,Channel Name,Youtuber Name,Total Videos,Best Video,Avg Video Length (min),Total Subscribers,Members Count,AI Generated Content (%),Neural Interface Compatible,Metaverse Integration Level,Quantum Computing Topics,Holographic Content Rating,Engagement Score,Content Value Index
0,Smith-Ross Labs,Eric Patel,68,VR Challenge: Review 2023,24.8,8264152,303319,9,True,Full,5,3D,130655.44,6.2
1,Sandoval PLC Hub,Cynthia Harrington,128,Nanotech Simulation: Analysis 2024,22.9,8768222,384629,62,False,NaN,4,3D,138624.73,21.4
2,"Jones, Moore and Ho Network",Amanda Walker,282,Metaverse Interface: Analysis 2024,24.0,6163386,361743,31,True,Advanced,6,1D,97442.53,13.5
3,Mitchell-Hooper Labs,Jessica Nelson MD,302,VR Protocol: Review 2023,24.6,4712268,58483,5,False,NaN,15,1D,74500.50,12.0
4,Wilson LLC Studios,Matthew Sherman,129,Nanotech Simulation: Review 2024,24.6,9592017,333873,63,True,NaN,12,3D,151648.85,27.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Flores-Daniel Studios,Jasmine Smith,106,AI Challenge: Experience 2023,22.0,2665835,267828,19,True,Full,1,3D,42146.59,6.4
4996,Spencer and Sons Studios,John Rasmussen,130,VR Challenge: Analysis 2023,26.3,136992,20019,67,True,Full,14,4D,2165.83,29.9
4997,Obrien-Roberts Studios,Lisa Burke,179,AI Challenge: Experience 2023,25.2,2314561,407346,99,True,Advanced,5,1D,36592.98,33.2
4998,King Ltd Hub,Steve Diaz,182,VR Synthesis: Showcase 2023,24.5,6954832,308313,1,True,Basic,9,4D,109955.22,6.6
4999,Henry Ltd Studios,Austin Tate,92,AI Simulation: Showcase 2025,25.2,6785166,23263,52,True,Full,8,3D,107272.81,21.2

#### **DataFrame** ---> A **DataFrame** is a **2-dimensional data structure** that consists of **multiple Pandas Series (columns)** sharing the same index.

##### **Note** :--> Combination of Multiple Series(Column)

#### **`squeeze()`** ---> Used to convert a **DataFrame with a single row or a single column** into a **Series**.
##### **Note** :--> squeeze parameters makes sure that the data is in Series Format

##### **Syntax** ---> `pd.read_csv("file.csv", squeeze=True)` *(Older versions of Pandas)*
##### **OR**
##### **Syntax** ---> `df.squeeze()` *(Recommended in newer versions of Pandas)*

##### **Note** ---> `squeeze()` ensures that the data is returned in **Series format** whenever possible.

In [92]:
type(pd.read_csv('youtube_one_column.csv'))

pandas.DataFrame

In [93]:
pd.read_csv('youtube_one_column.csv', squeeze=True)

TypeError: read_csv() got an unexpected keyword argument 'squeeze'

In [94]:
df=pd.read_csv('youtube_one_column.csv').squeeze('columns')

In [95]:
type(df)

pandas.Series

In [96]:
pd.read_csv('youtube_two_columns.csv')

           Youtuber Name  Total Videos
0             Eric Patel            68
1     Cynthia Harrington           128
2          Amanda Walker           282
3      Jessica Nelson MD           302
4        Matthew Sherman           129
...                  ...           ...
4995       Jasmine Smith           106
4996      John Rasmussen           130
4997          Lisa Burke           179
4998          Steve Diaz           182
4999         Austin Tate            92

[5000 rows x 2 columns]

#### **`index_col`** ---> Used to specify which column should be used as the **index** while reading a file into a Pandas DataFrame.

##### **Syntax** ---> `pd.read_csv("file.csv", index_col="column_name")`

###### **Note** ---> The specified column is removed from the normal columns and becomes the **row index** of the DataFrame.

In [97]:
dataframe=pd.read_csv('youtube_two_columns.csv', index_col='Youtuber Name').squeeze('columns')

In [99]:
df

0                   Smith-Ross Labs
1                  Sandoval PLC Hub
2       Jones, Moore and Ho Network
3              Mitchell-Hooper Labs
4                Wilson LLC Studios
                   ...
4995          Flores-Daniel Studios
4996       Spencer and Sons Studios
4997         Obrien-Roberts Studios
4998                   King Ltd Hub
4999              Henry Ltd Studios
Name: Channel Name, Length: 5000, dtype: str

In [98]:
dataframe

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
Jasmine Smith         106
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Name: Total Videos, Length: 5000, dtype: int64

### **Attributes in a Pandas Series**

#### **1. `.values`** ---> Returns only the values of the Series as a NumPy array.

#### **Syntax** ---> `series.values`

---

#### **2. `.index`** ---> Returns the index (labels) of the Series. ( `returns only the index values from the given column` ).

#### **Syntax** ---> `series.index`

---

#### **3. `.dtype`** ---> Returns the data type of the values stored in the Series. (`Dtype provides the idea about the data type of the values that you are storing`)

#### **Syntax** ---> `series.dtype`

---

#### **4. `.shape`** ---> Returns the shape (number of rows) of the Series.(`This attribute provides the idea about the row, column information`)

#### **Syntax** ---> `series.shape`

---

#### **5. `.size`** ---> Returns the total number of elements in the Series. (`This attributes provides the idea about the total number of rows inside the dataset`)

#### **Syntax** ---> `series.size`

---

#### **6. `.name`** ---> Returns or sets the name of the Series. (`This attribute provides the idea about name of the series`)

#### **Syntax** ---> `series.name`

---

#### **7. `.index.name`** ---> Returns or sets the name of the index.

#### **Syntax** ---> `series.index.name`

---

#### **8. `.ndim`** ---> Returns the number of dimensions of the Series. (`This attribute provides the idea about the dimension of the given dataset`)

#### **Syntax** ---> `series.ndim`

---

#### **9. `.empty`** ---> Returns `True` if the Series is empty; otherwise returns `False`.

#### **Syntax** ---> `series.empty`

---

#### **10. `.hasnans`** ---> Returns `True` if the Series contains missing (`NaN`) values; otherwise returns `False`.

#### **Syntax** ---> `series.hasnans`

---

#### **11. `.is_unique`** ---> Returns `True` if all values in the Series are unique; otherwise returns `False`. (`This provides us with the idea about wwhether if unique values are their or not inside the column`)

#### **Syntax** ---> `series.is_unique`

##### **Note** ---> It is used to check whether the Series contains any duplicate values.

In [100]:
df.values

<StringArray>
[                    'Smith-Ross Labs',                    'Sandoval PLC Hub',
         'Jones, Moore and Ho Network',                'Mitchell-Hooper Labs',
                  'Wilson LLC Studios',                   'Myers Ltd Network',
                   'Huber Inc Network',              'Baxter-Collins Studios',
                   'Morrow-Abbott Hub',               'Jackson Group Network',
 ...
                     'Cole-Sharp Labs', 'Sherman, Mcgee and Phillips Studios',
                      'Baker-Hill Hub',    'Francis, Davis and Jones Network',
     'Whitaker, Horn and Escobar Labs',               'Flores-Daniel Studios',
            'Spencer and Sons Studios',              'Obrien-Roberts Studios',
                        'King Ltd Hub',                   'Henry Ltd Studios']
Length: 5000, dtype: str

In [101]:
dataframe.values

array([ 68, 128, 282, ..., 179, 182,  92], shape=(5000,))

In [102]:
dataframe.index

Index(['Eric Patel', 'Cynthia Harrington', 'Amanda Walker',
       'Jessica Nelson MD', 'Matthew Sherman', 'Anna Berry', 'Richard Arnold',
       'Stephanie Potter', 'Teresa Aguirre', 'Anne Adkins',
       ...
       'Erin Bradley', 'Brooke Perez', 'Nicholas Jordan', 'Howard Phelps',
       'Sharon Graham', 'Jasmine Smith', 'John Rasmussen', 'Lisa Burke',
       'Steve Diaz', 'Austin Tate'],
      dtype='str', name='Youtuber Name', length=5000)

In [103]:
dataframe.dtype

dtype('int64')

In [104]:
dataframe=dataframe.astype('int32')

In [106]:
dataframe

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
Jasmine Smith         106
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Name: Total Videos, Length: 5000, dtype: int32

In [107]:
dataframe.size

5000

In [108]:
dataframe.shape

(5000,)

In [109]:
dataframe.ndim

1

In [110]:
dataframe.name

'Total Videos'

In [111]:
dataframe.is_unique

False

In [112]:
pd.Series([1,2,3,4,5]).is_unique

True

### **Series Methods**

#### **1. `head()`** ---> Returns the **top 5 rows** of a Series or DataFrame by default. It is useful for getting a quick preview of the dataset. If you want to display a specific number of rows, you can pass that number as an argument.

#### **Syntax** ---> `series.head()` or `series.head(n)`

##### **Example** ---> `series.head(10)` displays the first 10 rows, and `series.head(7)` displays the first 7 rows.

----

#### **2. `tail()`** ---> Returns the last **5 rows** of a Series or DataFrame by default. It is useful for previewing the end of the dataset.

#### **Syntax** ---> `series.tail()` or `series.tail(n)`

##### **Example** ---> `series.tail(10)` displays the bottom 10 rows, and `series.tail(7)` displays the bottom 7 rows.

----

#### **3. `sample()`** ---> Returns one or more random rows from a Series. It is useful for randomly inspecting the data. (`sample() provides any custom row from the dataset for us to preview it`)

#### **Syntax** ---> `series.sample()` or `series.sample(n)`

----

#### **4. `value_counts()`** ---> Counts the frequency of each unique value present in the Series. (`its provides the idea about the count of the values (categorical values), if i am having a column where the categorical value count i want to calculate then i can go with value_counts()`)

#### **Syntax** ---> `series.value_counts()`

----

#### **5. `sort_values()`** ---> Sorts the values of the Series in ascending order by default (`this method sort the value in an ascending manner. It can be useful for us for the numerical columns and also can even sort the value in descending manner as well).

#### **Syntax** ---> `series.sort_values()`

##### **Note** ---> Use `ascending=False` to sort in descending order.

----

#### **6. `sort_index()`** ---> Sorts the Series based on its index labels. (`this method sorts the index of the dataset`)

#### **Syntax** ---> `series.sort_index()`

----

#### **7. `unique()`** ---> Returns all the unique values present in the Series.

#### **Syntax** ---> `series.unique()`

----

#### **8. `nunique()`** ---> Returns the total number of unique values in the Series.

#### **Syntax** ---> `series.nunique()`

----

#### **9. `count()`** ---> Returns the total number of non-missing (non-NaN) values in the Series.

#### **Syntax** ---> `series.count()`

----

#### **10. `copy()`** ---> Creates a copy of the Series so that changes made to the new Series do not affect the original Series.

#### **Syntax** ---> `series.copy()`

In [113]:
dataframe

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
Jasmine Smith         106
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Name: Total Videos, Length: 5000, dtype: int32

In [114]:
dataframe.head()

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
Name: Total Videos, dtype: int32

In [115]:
dataframe.head(13)

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
Anna Berry             98
Richard Arnold        494
Stephanie Potter      133
Teresa Aguirre        316
Anne Adkins           140
David Clark            52
Kathleen Weeks        149
Melissa Kennedy        53
Name: Total Videos, dtype: int32

In [116]:
dataframe.tail()

Youtuber Name
Jasmine Smith     106
John Rasmussen    130
Lisa Burke        179
Steve Diaz        182
Austin Tate        92
Name: Total Videos, dtype: int32

In [117]:
df.head()

0                Smith-Ross Labs
1               Sandoval PLC Hub
2    Jones, Moore and Ho Network
3           Mitchell-Hooper Labs
4             Wilson LLC Studios
Name: Channel Name, dtype: str

In [118]:
df.tail()

4995       Flores-Daniel Studios
4996    Spencer and Sons Studios
4997      Obrien-Roberts Studios
4998                King Ltd Hub
4999           Henry Ltd Studios
Name: Channel Name, dtype: str

In [119]:
df.tail(11)

4989                   Knight and Sons Labs
4990                        Cole-Sharp Labs
4991    Sherman, Mcgee and Phillips Studios
4992                         Baker-Hill Hub
4993       Francis, Davis and Jones Network
4994        Whitaker, Horn and Escobar Labs
4995                  Flores-Daniel Studios
4996               Spencer and Sons Studios
4997                 Obrien-Roberts Studios
4998                           King Ltd Hub
4999                      Henry Ltd Studios
Name: Channel Name, dtype: str

In [120]:
df.sample()

2477    Murphy Ltd Studios
Name: Channel Name, dtype: str

In [121]:
df.sample(5)

3227                    Smith Ltd Network
1371    Porter, Armstrong and Walters Hub
3087      Sampson, Miller and Fisher Labs
4513                       Weeks-Hays Hub
2117                Farrell-Meyer Studios
Name: Channel Name, dtype: str

In [122]:
youtude=pd.read_csv('youtube_2025_dataset_202504061614.csv')

In [123]:
youtude

,Channel Name,Youtuber Name,Total Videos,Best Video,Avg Video Length (min),Total Subscribers,Members Count,AI Generated Content (%),Neural Interface Compatible,Metaverse Integration Level,Quantum Computing Topics,Holographic Content Rating,Engagement Score,Content Value Index
0,Smith-Ross Labs,Eric Patel,68,VR Challenge: Review 2023,24.8,8264152,303319,9,True,Full,5,3D,130655.44,6.2
1,Sandoval PLC Hub,Cynthia Harrington,128,Nanotech Simulation: Analysis 2024,22.9,8768222,384629,62,False,NaN,4,3D,138624.73,21.4
2,"Jones, Moore and Ho Network",Amanda Walker,282,Metaverse Interface: Analysis 2024,24.0,6163386,361743,31,True,Advanced,6,1D,97442.53,13.5
3,Mitchell-Hooper Labs,Jessica Nelson MD,302,VR Protocol: Review 2023,24.6,4712268,58483,5,False,NaN,15,1D,74500.50,12.0
4,Wilson LLC Studios,Matthew Sherman,129,Nanotech Simulation: Review 2024,24.6,9592017,333873,63,True,NaN,12,3D,151648.85,27.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Flores-Daniel Studios,Jasmine Smith,106,AI Challenge: Experience 2023,22.0,2665835,267828,19,True,Full,1,3D,42146.59,6.4
4996,Spencer and Sons Studios,John Rasmussen,130,VR Challenge: Analysis 2023,26.3,136992,20019,67,True,Full,14,4D,2165.83,29.9
4997,Obrien-Roberts Studios,Lisa Burke,179,AI Challenge: Experience 2023,25.2,2314561,407346,99,True,Advanced,5,1D,36592.98,33.2
4998,King Ltd Hub,Steve Diaz,182,VR Synthesis: Showcase 2023,24.5,6954832,308313,1,True,Basic,9,4D,109955.22,6.6
4999,Henry Ltd Studios,Austin Tate,92,AI Simulation: Showcase 2025,25.2,6785166,23263,52,True,Full,8,3D,107272.81,21.2

In [124]:
avg= youtude['Avg Video Length (min)']

In [ ]:
avg

0       24.8
1       22.9
2       24.0
3       24.6
4       24.6
        ...
4995    22.0
4996    26.3
4997    25.2
4998    24.5
4999    25.2
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [125]:
type(avg)

pandas.Series

In [126]:
avg.value_counts()

Avg Video Length (min)
24.1    276
23.8    264
23.9    256
24.2    253
24.0    251
       ...
19.9      1
27.3      1
28.0      1
21.0      1
20.7      1
Name: count, Length: 78, dtype: int64

In [127]:
avg

0       24.8
1       22.9
2       24.0
3       24.6
4       24.6
        ...
4995    22.0
4996    26.3
4997    25.2
4998    24.5
4999    25.2
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [128]:
avg.sort_values()

500     19.1
451     19.3
1713    19.9
171     20.6
3704    20.7
        ...
2748    28.0
925     28.1
364     28.3
1467    28.4
361     28.9
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [129]:
## parameter ---> ascending = False (sorting ---> desending )
avg.sort_values(ascending=False)

361     28.9
1467    28.4
364     28.3
925     28.1
2748    28.0
        ...
3704    20.7
171     20.6
1713    19.9
451     19.3
500     19.1
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [130]:
s = pd.Series([90,80,70], index=["C","A","B"])

print(s.sort_index())

A    80
B    70
C    90
dtype: int64

In [131]:
avg.unique()

array([24.8, 22.9, 24. , 24.6, 24.2, 23.2, 25.6, 23.1, 25.4, 26.9, 23.4,
       24.1, 24.9, 24.7, 23.6, 23.3, 25.5, 25.2, 23.7, 24.3, 23.8, 23.9,
       24.5, 23. , 25.9, 23.5, 25.8, 25.1, 24.4, 22.1, 22.8, 27. , 26.1,
       22.3, 25. , 26. , 22.4, 26.5, 26.6, 26.2, 20.6, 21.1, 22.2, 22.6,
       22.5, 27.9, 27.4, 25.7, 22. , 21.9, 22.7, 28.9, 28.3, 21.5, 19.3,
       25.3, 19.1, 21.6, 28.1, 21.7, 26.8, 26.7, 27.5, 28.4, 21.2, 21.4,
       19.9, 21.3, 26.4, 26.3, 27.3, 27.1, 21.8, 28. , 20.9, 21. , 20.7,
       27.2])

In [132]:
avg.nunique()

78

In [133]:
s = pd.Series([10,20,np.nan,30])

s.count()

np.int64(3)

In [134]:
s = pd.Series([10,20,30])

new_series = s.copy()

new_series[0] = 100

print(s)
print(new_series)

0    10
1    20
2    30
dtype: int64
0    100
1     20
2     30
dtype: int64

### **Method Chaining** ---> Method chaining is the process of using multiple methods together in a single statement. The output of the first method becomes the input for the next method, and the output of the second method becomes the input for the third method, and so on, until the required result is obtained.

#### **Syntax** ---> `object.method1().method2().method3()`

##### **`Note: -`** We will use multiple methods together to get the reuired value in way the first method's output will be second method input then 2nd method output will be 3rd method input

In [135]:
avg.sort_values(ascending=False).head(1)

361    28.9
Name: Avg Video Length (min), dtype: float64

In [136]:
avg.sort_values(ascending=False).head(1).values[0]

np.float64(28.9)

In [137]:
avg

0       24.8
1       22.9
2       24.0
3       24.6
4       24.6
        ...
4995    22.0
4996    26.3
4997    25.2
4998    24.5
4999    25.2
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [138]:
### In order to make a change in our data permanent ---> inplace

In [139]:
avg.sort_values()

500     19.1
451     19.3
1713    19.9
171     20.6
3704    20.7
        ...
2748    28.0
925     28.1
364     28.3
1467    28.4
361     28.9
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [140]:
avg_data = avg.copy()

In [141]:
avg_data

0       24.8
1       22.9
2       24.0
3       24.6
4       24.6
        ...
4995    22.0
4996    26.3
4997    25.2
4998    24.5
4999    25.2
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [142]:
avg_data.sort_values(inplace=True)

In [143]:
avg_data

500     19.1
451     19.3
1713    19.9
171     20.6
3704    20.7
        ...
2748    28.0
925     28.1
364     28.3
1467    28.4
361     28.9
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [144]:
dataframe.sort_index()

Youtuber Name
Aaron Archer        136
Aaron Bishop        151
Aaron Brown          51
Aaron Burns         314
Aaron Carrillo      210
                   ...
Zachary Phillips    478
Zachary Russell      81
Zachary Shelton     446
Zoe Peterson         78
Zoe Smith            83
Name: Total Videos, Length: 5000, dtype: int32