In [ ]:
pip install pandas

Requirement already satisfied: pandas in c:\users\abhis\appdata\local\programs\python\python313\lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\abhis\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\abhis\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\abhis\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\abhis\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
import numpy as np
import pandas as pd

### **Pandas Series** ---> A **Pandas Series** is a **one-dimensional labeled array** that stores data in a **single column**, similar to a column in **Excel** or **Google Sheets**, where each value has an associated **index (label)**.

### Pandas Series is a column of data in Table like in Excel or Google Sheets with labels called as indexed attached to each value.

In [ ]:
pd.Series([40,50,60],index=["Bread","Milk","Butter"],name="Price of Grocery Items")

Bread     40
Milk      50
Butter    60
Name: Price of Grocery Items, dtype: int64

### **Series** ---> A **Pandas Series** is a **one-dimensional (1-D) labeled array** that can store **any type of data**, such as **integers, floating-point numbers, strings (objects), booleans, or mixed data types**.

#### **Features of a Series**
- **1-D Array** ---> Stores data in a single column.
- **Indexed** ---> Each value has an associated index (label).
- **Supports Multiple Data Types** ---> Can store integers, floats, strings, booleans, or mixed data.

#### Data Type ---> Integers -----> Data in a Series(Column) ---> Quantity of items in the stock
#### Data Type ---> Float -----> Data in a Series(Column) ---> Price or Product Ratings
#### Data Type ---> Strings -----> Column ---> Product Name
#### Data Type ---> Boolean -----> Column ---> Is item in Stock ?
#### Data Type ---> Dates/ times -----> Column---> Expiry Dates or Sale Dates
#### Mixed Types ---> Milk,40,True

### **Common Data Types in a Pandas Series**

#### **Integer (`int`)** ---> Used to store **whole numbers**, such as the **quantity of items in stock**.

#### **Float (`float`)** ---> Used to store **decimal numbers**, such as **product prices** or **ratings**.

#### **String (`str` or `object`)** ---> Used to store **text data**, such as **product names** or **customer names**.

#### **Boolean (`bool`)** ---> Used to store **True/False** values, such as **whether an item is in stock**.

#### **Date/Time (`datetime`)** ---> Used to store **dates and times**, such as **expiry dates**, **sale dates**, or **order dates**.

#### **Mixed Data Types** ---> A Series can also store **different types of data together**, for example: `"Milk"`, `40`, `True`.

### Creating a Series in Multiple Ways
#### 1. Lists
#### 2. Numpy Array
#### 3. Dictionary
#### 4. Custom Index
#### 5. Scalar Value

In [ ]:
## Series From List

country = ['India', 'China', 'USA', 'Nepal']

pd.Series(country)

0    India
1    China
2      USA
3    Nepal
dtype: str

In [ ]:
batsman_runs=[48,64,72,98,114,183]

pd.Series(batsman_runs,dtype='int32')

0     48
1     64
2     72
3     98
4    114
5    183
dtype: int32

In [ ]:
subject_name=['Maths','Physics','Chemisry','Biology','English']
subject_marks=[90,93,64,90,98]

pd.Series(data=subject_marks,index=subject_name,name='Subject Marks data',dtype='int32')

Maths       90
Physics     93
Chemisry    64
Biology     90
English     98
Name: Subject Marks data, dtype: int32

In [ ]:
### creating an series using a Numpy Array
values=np.arange(10,21)
pd.Series(values)

0     10
1     11
2     12
3     13
4     14
5     15
6     16
7     17
8     18
9     19
10    20
dtype: int64

### **Dictionary to Series**

#### A **Dictionary** is a Python data structure that stores data in **key-value pairs**.

#### When a **dictionary is converted into a Pandas Series**, the **keys become the index (labels)** and the **values become the data**.

#### Since the dictionary already contains **keys**, we **do not need to explicitly specify the index**.

#### **Syntax** ---> `pd.Series(dictionary)`
## ------------------------ Notes ------------------------
#### Distionary to Series

##### Dictionary is another Data Structure that stores data in a key value pair and just beacuse it stores the data in a key value pair so we don't have to explicitly mention the index

In [ ]:
data_items={'Maths':78,'English':92,'Chemistry':64}
pd.Series(data_items)

Maths        78
English      92
Chemistry    64
dtype: int64

In [ ]:
## custom index to Series
values=[1,2,3,4,5]
pd.Series(data=values,index=['a1','a2','a3','a4','a5'])

a1    1
a2    2
a3    3
a4    4
a5    5
dtype: int64

In [ ]:
## Scalar Value inside an Series

pd.Series(4,index=['a','b','c','d','e'])

a    4
b    4
c    4
d    4
e    4
dtype: int64

In [ ]:
## read_csv()---> This function reads content from the csv file in pandas so that we can perform the operations on the data or we can perform effective analysis.
youtube = pd.read_csv('youtube_2025_dataset_202504061614.csv')
youtube

,Channel Name,Youtuber Name,Total Videos,Best Video,Avg Video Length (min),Total Subscribers,Members Count,AI Generated Content (%),Neural Interface Compatible,Metaverse Integration Level,Quantum Computing Topics,Holographic Content Rating,Engagement Score,Content Value Index
0,Smith-Ross Labs,Eric Patel,68,VR Challenge: Review 2023,24.8,8264152,303319,9,True,Full,5,3D,130655.44,6.2
1,Sandoval PLC Hub,Cynthia Harrington,128,Nanotech Simulation: Analysis 2024,22.9,8768222,384629,62,False,NaN,4,3D,138624.73,21.4
2,"Jones, Moore and Ho Network",Amanda Walker,282,Metaverse Interface: Analysis 2024,24.0,6163386,361743,31,True,Advanced,6,1D,97442.53,13.5
3,Mitchell-Hooper Labs,Jessica Nelson MD,302,VR Protocol: Review 2023,24.6,4712268,58483,5,False,NaN,15,1D,74500.50,12.0
4,Wilson LLC Studios,Matthew Sherman,129,Nanotech Simulation: Review 2024,24.6,9592017,333873,63,True,NaN,12,3D,151648.85,27.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Flores-Daniel Studios,Jasmine Smith,106,AI Challenge: Experience 2023,22.0,2665835,267828,19,True,Full,1,3D,42146.59,6.4
4996,Spencer and Sons Studios,John Rasmussen,130,VR Challenge: Analysis 2023,26.3,136992,20019,67,True,Full,14,4D,2165.83,29.9
4997,Obrien-Roberts Studios,Lisa Burke,179,AI Challenge: Experience 2023,25.2,2314561,407346,99,True,Advanced,5,1D,36592.98,33.2
4998,King Ltd Hub,Steve Diaz,182,VR Synthesis: Showcase 2023,24.5,6954832,308313,1,True,Basic,9,4D,109955.22,6.6
4999,Henry Ltd Studios,Austin Tate,92,AI Simulation: Showcase 2025,25.2,6785166,23263,52,True,Full,8,3D,107272.81,21.2

## **Creating a DataFrame**

### **1. From a Dictionary** ---> The keys become the **column names**, and the values become the **column data**.

#### **Syntax** ---> `pd.DataFrame(dictionary)`

In [ ]:
subs = youtube['Total Subscribers']
avg = youtube['Avg Video Length (min)']
dataframe = df.set_index("Youtuber Name")["Total Videos"]

In [ ]:
# dataframe = pd.read_csv('youtube_two_columns.csv')

In [ ]:
subs

0       8264152
1       8768222
2       6163386
3       4712268
4       9592017
         ...
4995    2665835
4996     136992
4997    2314561
4998    6954832
4999    6785166
Name: Total Subscribers, Length: 5000, dtype: int64

## **Mathematical Functions in Pandas**

#### **1. `sum()`** ---> Used to calculate the **sum of all values** present in a Series.

#### **Syntax** ---> `series.sum()`

---

#### **2. `product()`** ---> Used to calculate the **product (multiplication)** of all values present in a Series.

#### **Syntax** ---> `series.product()`

---

#### **3. `mean()`** ---> Used to calculate the **average (mean)** of all values present in a Series.

#### **Syntax** ---> `series.mean()`

---

#### **4. `median()`** ---> Used to calculate the **median (middle value)** of all values present in a Series.
##### Note :---> Median also provides the idea about the average of the data. For coming up with median, we need to SORT the value in Ascending manner and then the middle value after sorting the data 

#### **Syntax** ---> `series.median()`

---

#### **5. `mode()`** ---> Used to calculate the **most frequently occurring value(s)** in a Series.

#### **Syntax** ---> `series.mode()`

---

#### **6. `std()`** ---> Used to calculate the **standard deviation** of the values present in a Series.
##### Note :---> If i need to get the idea that how the values inside the series are distributed from the average or mean value then we can come up with the standard deviation.

#### **Syntax** ---> `series.std()`

---

#### **7. `Variance [var()]`** ---> Used to calculate the **variance** of the values present in a Series.
##### Note :---> Variance also rpvides the insight about the distribution of the data from the mean value and variance is the square of the standard deviation
##### varaince = std ** 2

#### **Syntax** ---> `series.var()`

---

#### **8. `min()`** ---> Used to find the **minimum value** present in a Series.

#### **Syntax** ---> `series.min()`

---

#### **9. `max()`** ---> Used to find the **maximum value** present in a Series.

#### **Syntax** ---> `series.max()`

---

#### **10. `describe()`** ---> Used to display a **statistical summary** of the numerical values in a Series.
##### Note :---> describe fn provides the idea about the summary of the important mathematical calculations for the data

#### **Syntax** ---> `series.describe()`

##### **`describe()` Includes:**
- **count** ---> Total number of non-null values.
- **mean** ---> Average of all values.
- **std** ---> Standard deviation of the values.
- **min** ---> Smallest value in the Series.
- **25%** ---> First Quartile (25th Percentile).
- **50%** ---> Median (50th Percentile).
- **75%** ---> Third Quartile (75th Percentile).
- **max** ---> Largest value in the Series.

---

#### **11. `cumsum()`** ---> Used to calculate the **cumulative sum** of the values in a Series.

#### **Syntax** ---> `series.cumsum()`

---

#### **12. `cumprod()`** ---> Used to calculate the **cumulative product** of the values in a Series.

#### **Syntax** ---> `series.cumprod()`

---

#### **13. `abs()`** ---> Used to return the **absolute (positive)** value of each element in a Series.

#### **Syntax** ---> `series.abs()`

---

#### **14. `round()`** ---> Used to round the values in a Series to the specified number of decimal places.

#### **Syntax** ---> `series.round(decimals)`

---

#### **15. `count()`** ---> Used to count the **number of non-null values** present in a Series.

#### **Syntax** ---> `series.count()`

---

In [ ]:
subs.sum()

np.int64(25292407967)

In [ ]:
subs.product()

np.int64(0)

In [ ]:
subs.sort_values()

3595       1755
3204       2910
2470       8649
4584       9029
2615       9436
         ...
3969    9991900
380     9992512
1177    9995049
3593    9999559
1931    9999975
Name: Total Subscribers, Length: 5000, dtype: int64

In [ ]:
subs.mean()

np.float64(5058481.5934)

In [ ]:
subs.median()

np.float64(5105967.0)

In [ ]:
subs.mode()

0          1755
1          2910
2          8649
3          9029
4          9436
         ...
4995    9991900
4996    9992512
4997    9995049
4998    9999559
4999    9999975
Name: Total Subscribers, Length: 5000, dtype: int64

In [ ]:
avg

0       24.8
1       22.9
2       24.0
3       24.6
4       24.6
        ...
4995    22.0
4996    26.3
4997    25.2
4998    24.5
4999    25.2
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [ ]:
avg.mode()

0    24.1
Name: Avg Video Length (min), dtype: float64

In [ ]:
avg.std()

np.float64(0.8745549483431755)

In [ ]:
avg.var()

np.float64(0.7648463576715343)

In [ ]:
avg.min()

np.float64(19.1)

In [ ]:
avg.max()

np.float64(28.9)

In [ ]:
youtube.describe()

,Total Videos,Avg Video Length (min),Total Subscribers,Members Count,AI Generated Content (%),Quantum Computing Topics,Engagement Score,Content Value Index
count,5000.00000,5000.000000,5.000000e+03,5000.00000,5000.000000,5000.000000,5000.000000,5000.000000
mean,274.43340,24.004540,5.058482e+06,249082.01980,49.328600,10.061400,79974.100470,21.841560
std,131.71675,0.874555,2.890895e+06,143555.47327,29.444246,6.093953,45704.767088,9.863744
min,50.00000,19.100000,1.755000e+03,143.00000,0.000000,0.000000,27.750000,0.000000
25%,159.00000,23.500000,2.547991e+06,127000.75000,24.000000,5.000000,40283.490000,14.200000
50%,274.00000,24.000000,5.105967e+06,252320.50000,49.000000,10.000000,80724.840000,21.800000
75%,389.00000,24.500000,7.541903e+06,371419.25000,76.000000,15.000000,119236.752500,29.700000
max,500.00000,28.900000,9.999975e+06,499991.00000,100.000000,20.000000,158098.630000,44.000000

In [ ]:
avg.describe()

count    5000.000000
mean       24.004540
std         0.874555
min        19.100000
25%        23.500000
50%        24.000000
75%        24.500000
max        28.900000
Name: Avg Video Length (min), dtype: float64

### **Indexing in a Pandas Series** *(To access one or more values from a Series)*

#### **1. Positive Indexing** ---> Works just like Python lists. Indexing starts from **0** and moves from **left to right**.

##### Note --> NO Negative Indexing

#### **Syntax** ---> `series[index]`

---

#### **2. Negative Indexing** ---> Indexing starts from **-1** and moves from **right to left**.

#### **Syntax** ---> `series[-index]`

---

#### **3. Label-Based Indexing** ---> Access values using their **index labels** instead of position.

#### **Syntax** ---> `series[label]`

---

#### **4. Multiple Value Indexing** ---> Access multiple values by passing a **list of indices or labels**.

#### **Syntax** ---> `series[[index1, index2]]` or `series[[label1, label2]]`

---

#### **5. Slicing** ---> Used to access a **range of values** from a Series using the slicing operator (`:`).

#### **Syntax** ---> `series[start:stop:step]`

#### **Note** ---> The **start index is included**, while the **stop index is excluded**.

---

#### **6. Label-Based Slicing** ---> Used to access a **range of values using index labels**.

#### **Syntax** ---> `series["start_label":"end_label"]`

#### **Note** ---> In **label-based slicing**, **both the start and end labels are included**.

---

#### **7. Fancy Indexing** ---> Used to access **multiple non-consecutive values** from a Pandas Series by passing a **list of index positions or labels**.

#### **Syntax (Position-Based)** ---> `series[[index1, index2, index3]]`

#### **Syntax (Label-Based)** ---> `series[[label1, label2, label3]]`

In [ ]:
avg

0       24.8
1       22.9
2       24.0
3       24.6
4       24.6
        ...
4995    22.0
4996    26.3
4997    25.2
4998    24.5
4999    25.2
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [ ]:
avg[0]

np.float64(24.8)

In [ ]:
avg[5]

np.float64(24.2)

In [ ]:
avg[-1]

KeyError: -1

In [ ]:
avg[7:18]

7     25.6
8     23.1
9     24.2
10    22.9
11    25.4
12    26.9
13    23.4
14    24.1
15    24.9
16    24.7
17    24.8
Name: Avg Video Length (min), dtype: float64

In [ ]:
## If i want the values skipped as a certain value
avg[2:21:2]

2     24.0
4     24.6
6     23.2
8     23.1
10    22.9
12    26.9
14    24.1
16    24.7
18    23.6
20    24.8
Name: Avg Video Length (min), dtype: float64

In [ ]:
### Reverse values in series
avg[::-1]

4999    25.2
4998    24.5
4997    25.2
4996    26.3
4995    22.0
        ...
4       24.6
3       24.6
2       24.0
1       22.9
0       24.8
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [ ]:
avg[[2,4,9]]

2    24.0
4    24.6
9    24.2
Name: Avg Video Length (min), dtype: float64

In [ ]:
avg[[55,1008,79,56,65]]

55      24.9
1008    23.3
79      25.1
56      23.0
65      25.8
Name: Avg Video Length (min), dtype: float64

In [ ]:
dataframe

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
Jasmine Smith         106
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Name: Total Videos, Length: 5000, dtype: int64

In [ ]:
dataframe['Steve Diaz']

np.int64(182)

In [ ]:
dataframe['Jasmine Smith']

Youtuber Name
Jasmine Smith    244
Jasmine Smith    418
Jasmine Smith    106
Name: Total Videos, dtype: int64

## **Editing a Series** *(Bringing changes to the values stored inside a Series)*

#### **Using Indexing** ---> Used to change the value at a particular index in the Series.

#### **Syntax** ---> `series[index] = new_value`

In [ ]:
dataframe['Cynthia Harrington'] = 75

In [ ]:
dataframe

Youtuber Name
Eric Patel             68
Cynthia Harrington     75
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
Jasmine Smith         106
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Name: Total Videos, Length: 5000, dtype: int64

In [ ]:
### if Indexing doesn't exist
dataframe['Abhi kumar verma']=78

In [ ]:
dataframe

Youtuber Name
Eric Patel             68
Cynthia Harrington     75
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Abhi kumar verma       78
Name: Total Videos, Length: 5001, dtype: int64

In [ ]:
## Slicing in Series ---> df[2:7]=100 ---> 100 value will be associated for index 2 to 6

In [ ]:
dataframe

Youtuber Name
Eric Patel             68
Cynthia Harrington     75
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Abhi kumar verma       78
Name: Total Videos, Length: 5001, dtype: int64

In [ ]:
avg[1:5]=28

In [ ]:
avg

0       24.8
1       28.0
2       28.0
3       28.0
4       28.0
        ...
4995    22.0
4996    26.3
4997    25.2
4998    24.5
4999    25.2
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [ ]:
## Fancy Indexing ---> df[2,4,8]=[45,84,79]

In [ ]:
avg[[4,4998,4996,0]]=[25,21,20,24]

In [ ]:
avg

0       24.0
1       28.0
2       28.0
3       28.0
4       25.0
        ...
4995    22.0
4996    20.0
4997    25.2
4998    21.0
4999    25.2
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [ ]:
## Indexing Labelling
dataframe

Youtuber Name
Eric Patel             68
Cynthia Harrington     75
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Abhi kumar verma       78
Name: Total Videos, Length: 5001, dtype: int64

In [ ]:
dataframe[['Eric Patel','Jessica Nelson MD','Abhi kumar verma']]=[45,250,100]

InvalidIndexError: Reindexing only valid with uniquely valued Index objects

False